RadioAstronomySoftwareGroup/pyradiosky

ci/tests.yaml
pyradiosky/skymodel.py
pyradiosky/tests/test_skymodel.py

Includes the `LunarTopo` frame and `MoonLocation` class from `lunarsky` in SkyModel's transformations.

Support local coordinate transformations on the Moon

---

.github/CONTRIBUTING.md
.github/PULL_REQUEST_TEMPLATE/bug_fix.md
.github/PULL_REQUEST_TEMPLATE/build_ci_change.md
.github/PULL_REQUEST_TEMPLATE/documentation.md
.github/PULL_REQUEST_TEMPLATE/new_feature.md
.github/PULL_REQUEST_TEMPLATE/other.md
.github/PULL_REQUEST_TEMPLATE/version_change.md
CODE_OF_CONDUCT.md
README.md

@jpober we put this together as a group on the telecon today, so I'm nominating you as the reviewer.
closes #45 
closes #18

Add readme, contributing guide, pull request templates and code of conduct

---

pyradiosky/skymodel.py
pyradiosky/tests/test_skymodel.py

A recent change I made stuck the full Stokes array into the recarray in the `skymodel_to_array` function. It makes sense for ensuring the full polarization info is kept for all components, but does effectively quadruple the memory usage. This meant that a sky model that Daniya was using could not longer work within MPI's size constraints.
As this is holding up reference simulations, this should be a priority.
This PR separates the Stokes parameters in the recarray, so instead of one column `flux_density` with shape `(Ncomponents, 4, Nfreqs)`, there are four columns `I`, `Q`, `U`, and `V` with shape `(Ncomponents, Nfreqs)`. Each column will only be kept in the recarray a component has nonzero flux in that Stokes parameter. So if all source components are unpolarized, the recarray will only …

Separate polarization components in recarray

---

README.md
ci/tests.yaml
environment.yaml
pyradiosky/tests/test_utils.py
pyradiosky/utils.py
scripts/download_gleam.py
setup.py

Add a script to download the GLEAM catalog as a VOTable from Vizier.
Make it easy to get the GLEAM catalog with all the relevant columns.

Add a script to download GLEAM

---

.github/workflows/build_docs.yaml
.github/workflows/testsuite.yaml
.gitignore
.readthedocs.yml
CHANGELOG.md
README.md
ci/docs.yaml
ci/pyuvsim.yaml
ci/tests.yaml
docs/Makefile
docs/conf.py
docs/developer_docs.rst
docs/make.bat
docs/make_index.py
docs/make_parameters.py
docs/skymodel.rst
docs/utility_functions.rst
environment.yaml
pyradiosky/skymodel.py
setup.cfg
setup.py

---
name: Documentation
about: Update or improve the documentation.
labels: documentation
---
Add Sphinx docs hosted on ReadTheDocs (https://pyradiosky.readthedocs.io/en/latest/ -- go to the `add_rtd` version to see what's being built on this branch) and a github action to build them for a CI check.
Also add some support for doc development via an `extras_require` section and update readme and the environment.yaml, both for the docs changes and for `lunarsky` now being on PyPI.
We need to have API docs.
closes #23
partially addresses #22

Add Sphinx docs hosted on GitHub Pages

---

CHANGELOG.md

Update the changelog for a new release.

update changelog for a new release

---

pyradiosky/skymodel.py
pyradiosky/tests/test_skymodel.py

Check that the required frequency parameters are set in `__init__` (depending on spectral_type).
closes #66

Check that frequency information is included as required in `__init__`

---

.github/workflows/externaltests.yaml
.github/workflows/testsuite.yaml

Separate out the pyuvsim tests into a separate workflow to make it clearer which tests are on this repo and to make it easier to rerun the parts as appropriate.

Move pyuvsim tests to a separate github actions workflow

---

README.md
pyradiosky/skymodel.py
pyradiosky/tests/test_skymodel.py
pyradiosky/tests/test_utils.py
pyradiosky/utils.py

Add versioning plan to the readme and update deprecation warnings to give a version when the deprecation will be done.

Add versioning detail to readme, add version to deprecation warnings

---

CHANGELOG.md

Update the changelog so we can release version 0.1.0.

update changelog for new version

---

.github/PULL_REQUEST_TEMPLATE.md
.github/original_pr_templates/bug_fix.md
.github/original_pr_templates/build_ci_change.md
.github/original_pr_templates/documentation.md
.github/original_pr_templates/new_feature.md
.github/original_pr_templates/other.md
.github/original_pr_templates/version_change.md
.github/workflows/build_docs.yaml
README.md
docs/make_index.py
pyradiosky/branch_scheme.py

We recently changed the default branch name from `master` to `main`. This PR updates all the references to the `master` branch to point to the `main` branch.

Fix all the references to the master branch

---

.github/workflows/build_docs.yaml
.github/workflows/externaltests.yaml
.github/workflows/publish-to-test-pypi.yaml
.github/workflows/testsuite.yaml
docs/make_index.py
docs/make_parameters.py
pyradiosky/tests/test_spherical_coords_transforms.py

Replaces deprecated set-env and add-path commands with newer files for github actions.

Remove deprecated GH action commands

---

scripts/make_flat_spectrum_eor.py

Adds a script which can be used to make a SkyModel object containing a noiselike EoR signal. These have a flat cosmological power spectrum over the range of k_par corresponding with the range of redshifts in the file.
The amplitude of this spectrum is σ^2 dV_0, where σ^2 is a set variance parameter and dV_0 is the voxel volume at a chosen "reference frequency".
This can be run on its own, in which case it makes a SkyModel with several default parameters, or the function can be imported and used 
Simulations of EoR-like signals require EoR-like signals to simulate. This provides a simple EoR model which, although non-physical, can be useful.

adding a script to make flat-spectrum EoR models

---

pyradiosky/skymodel.py
pyradiosky/tests/test_skymodel.py

This fixes several bugs identified by writing and read back a skyh5 file after calling `healpix_to_point`.
Fixes #128

Fix a series of bugs related to using skyh5 after healpix_to_point

---

CHANGELOG.md
pyradiosky/skymodel.py
pyradiosky/tests/test_skymodel.py

Add a `concat` method for combining catalogs.
Todo: needs changelog updates
closes #39

add concat method and testing

---

pyradiosky/skymodel.py

Fix documentation about Jy/sr units

---

CHANGELOG.md
pyradiosky/skymodel.py
pyradiosky/tests/test_skymodel.py

closes #131 
closes #135
Added a clobber keyword to the writer. 
Allows user to overwrite the default healpix ra/dec with lots of warnings.

Milestone bug fixes

---

CHANGELOG.md
pyradiosky/skymodel.py
pyradiosky/tests/test_skymodel.py

Correct bug in unit string conversion

---

CHANGELOG.md

Update the changelog to mark a new release.

Update changelog for a new release (0.1.2)

---

.github/workflows/testsuite.yaml

bump codecov action from 1.5.2 to 2.0.2

---

CHANGELOG.md
pyradiosky/skymodel.py
pyradiosky/tests/test_skymodel.py

This contains several changes related to handling healpix objects.
- Make ra and dec not be required parameters on healpix objects. This reduces the amount of warnings about ra/decs being assigned to healpix objects (introduced in #144). This also reduces the likelihood of having ra/decs that do not match actual healpix locations.
- Add a `get_ra_dec` method which returns the ra and dec for each component. On a healpix object, this uses `astropy_healpix` to get the ra and dec values for each healpix pixel on the object. On a point object it just returns the ra and dec on the object.
- rename (with deprecation) the `point_to_healpix` method to `_point_to_healpix` because it's really only intended to be used internally to undo the `healpix_to_point` method.
- add the `assign_to_healpix` …

Make ra, dec not required on healpix objects, add `assign_to_healpix` method

---

scripts/make_flat_spectrum_eor.py

- Fix a bug related to improper indexing into the redshift.
- Fix a bug related to improper ordering of maps along the frequency axis
- Improve readability and input checking
- Save out as a skyh5 file rather than a deprecated healvis-style hdf5 file
fixes #163

Fix bug and improve readability of flat spectrum script

---

scripts/make_flat_spectrum_eor.py

We divide by the scale value, instead of multiplying

Fix make flat spectrum eor script

---

.github/workflows/testsuite.yaml
.pre-commit-config.yaml
ci/linting.yaml
docs/make_index.py
pyradiosky/tests/test_skymodel.py
pyradiosky/tests/test_utils.py
scripts/make_flat_spectrum_eor.py

There are minor formatting updates associated with these updates.

update the pre-commit package versions

---

.github/workflows/externaltests.yaml
.github/workflows/publish-to-test-pypi.yaml
.github/workflows/testsuite.yaml
ci/publish.yaml

- Speed things up with Mamba.
- Update how we build our package to use the `build` package rather than the pep517 package because that is the preferred method now.

Use Mamba in CI, update how we build the distribution

---

README.md

Add NSF acknowledgements to README.
Mention UW and Brown NSF CSSI grant numbers.
Better reporting for NSF.

Add NSF acknowledgments.

---

CHANGELOG.md
pyradiosky/__init__.py
pyradiosky/skymodel.py
pyradiosky/tests/test_skymodel.py
pyradiosky/tests/test_utils.py
pyradiosky/utils.py

Prepare to release version 0.2.0:
- update the changelog to add the new release
- remove deprecated code marked to be removed in v0.2.0
- update the changelog to list the removed items.
This also includes a one-line fix for a bug when using the branch this in pyuvdata PR: https://github.com/RadioAstronomySoftwareGroup/pyuvdata/pull/1252
The problem is that PR added more handling for a silent keyword in the parameter __eq__ method so we needed to add it in the `TelescopeLocationParameter` that derives from UVParameter.
closes #85

New version

---

CHANGELOG.md
README.md
ci/min_deps.yaml
ci/min_versions.yaml
ci/publish.yaml
ci/tests.yaml
environment.yaml
pyradiosky/skymodel.py
pyradiosky/tests/test_skymodel.py
setup.py

Change to an approach more similar to what we did in pyuvdata. This helps make it more clear which library is actually being used (astropy or lunarsky) for various operations. In this process I also identified and fixed some bugs related to properly rotating polarized sources for lunar locations.
Also require the newest version of lunarsky to get rid of astropy deprecation warnings.

Better handling for lunar locations

---

CHANGELOG.md

Need to get out a new version!

Prepare for version 0.3.1

---

README.md

I just noticed a few anachronisms in the readme and thought we should fix them before the JOSS review.

Some minor readme fixes

---

.github/workflows/externaltests.yaml

The conda yaml name recently changed in pyuvsim. Update it here so the CI runs.

update the pyuvsim yaml name

---

.github/workflows/testsuite.yaml
CHANGELOG.md
README.md
ci/full_deps.yaml
ci/min_deps.yaml
ci/min_versions.yaml
ci/publish.yaml
environment.yaml
scripts/download_gleam.py
scripts/make_flat_spectrum_eor.py
setup.py
src/pyradiosky/skymodel.py
src/pyradiosky/spherical_coords_transforms.py
src/pyradiosky/utils.py
tests/conftest.py
tests/test_skymodel.py
tests/test_spherical_coords_transforms.py
tests/test_utils.py

As pointed out by our JOSS reviewer in #238, several files said they were licensed under the 3-clause BSD license when our actual license is the 2-clause BSD license. I fixed those and added licensing info to one script that was missing the info.
Conflicts between the `lunarsky` and `pyuvdata` versions also forced me to update a bunch of dependencies.
fixes #238 

Fix several places where files listed the wrong license type

---

CHANGELOG.md
docs/conf.py
setup.py

Prepare for v1.0!
JOSS requires us to make a new version to point the paper to.

Prepare for version 1.0

---

paper.bib
paper.md

ref: https://github.com/openjournals/joss-reviews/issues/6503

Edit for JOSS review

---

.flake8
.github/workflows/testsuite.yaml
pyproject.toml
setup.py
tests/test_spherical_coords_transforms.py

Convert to using pyproject.toml as much as possible. This is both to follow current best practices and also to try to fix recent setuptools_scm issues.
Also fixed two things in the actions yaml that seem to have fixed the MacOS builds:
- fetching the full-depth repo (without this calls to `git describe` fail)
- calling `git describe` and `git version` right before the install step. This seems to fix a problem on Mac builds where setuptools_scm's call to git was timing out. I don't really understand why...

Convert to using pyproject.toml as much as possible.

---

tests/test_skymodel.py

In version 3, the import for pyuvdata's warning_checker function will be different, this handles that change.

Fixes for compatibility with future pyuvdata

---

CHANGELOG.md
README.md
ci/full_deps.yaml
ci/min_deps.yaml
ci/min_versions.yaml
ci/publish.yaml
environment.yaml
pyproject.toml

- Update the minimum dependencies in all the places to match the `pyproject.toml` (mostly setuptools_scm but also lunarsky in one place).
-  Update the minimum dependencies: setuptools_scm>=8.1 and scipy>=1.8 to fix errors in the min_versions CI
- Prepare for a new version because we need to get out a version that is compatible with numpy 2.0

Prepare for v1.0.1

---

docs/tutorial.rst
src/pyradiosky/skymodel.py
tests/test_skymodel.py

Add info to docstring and tutorial about what text files do not support. Also add errors to prevent losing info by writing to text files when info would be lost.
closes #187

Clarify that text files don't support extended model groups

---

CHANGELOG.md
src/pyradiosky/skymodel.py

Lunarsky does a bunch of calculations and caching on import. So we should only import it if it's actually needed.

only import lunarsky if it's actually needed

---

.gitignore
README.md

The GitHub badge is broken because Github changed the badge url. RTD was missing.

Fix the github action badge, add RTD badge

---

pyproject.toml
tests/test_skymodel.py

- Update pre-commit isort options to be compatible with black options
- remove warning filtering that's no longer needed.

Cleanup several minor things
