RadioAstronomySoftwareGroup/pyradiosky

- .github/workflows/testsuite.yaml
- ci/pyuvsim.yaml
- ci/tests.yaml
- environment.yaml
- pyradiosky/skymodel.py
- pyradiosky/spherical_coords_transforms.py
- pyradiosky/tests/test_skymodel.py
- pyradiosky/tests/test_spherical_coords_transforms.py
- pyradiosky/tests/test_utils.py
- pyradiosky/utils.py
- setup.py
Tests fail because astropy no longer warns about Jy/beam unit in VOTable read.
closes #32
closes #31
closes #30
closes #28
closes #27
closes #14
> remove warning check for astropy votable

- .github/workflows/testsuite.yaml
- .pre-commit-config.yaml
- ci/linting.yaml
- pyradiosky/skymodel.py
- pyradiosky/spherical_coords_transforms.py
- pyradiosky/tests/test_skymodel.py
- pyradiosky/tests/test_spherical_coords_transforms.py
- pyradiosky/tests/test_utils.py
- pyradiosky/utils.py
- setup.cfg
- setup.py
Adds pre-commit, and also a whole lot of automatic flake8 goodness.
Fixes #40 
Fixes #29 
Since this changes a lot of files, it might be a bit tricky to merge with other PRs on the loose. 
So far, I've added 
```
- flake8-docstrings
- flake8-rst-docstrings
- flake8-comprehensions
- flake8-black
- flake8-builtins
- flake8-copyright
```
and made changes in the code to make these pass.
I think we should also enable `pep8-naming` and `flake8-eradicate`, but I want to hear others' opinions first. Adding pep8-naming gives the following errors:
```
pyradiosky/skymodel.py:200:10: N806 variable 'R_screwy' in function should be lowercase
pyradiosky/skymodel.py:201:10: N806 variable 'R_really_orthogonal' in function should be lowercase
pyradiosky/skymodel.py:204:10: N806 variable …
```
> Pre commit

- pyradiosky/__init__.py
- pyradiosky/skymodel.py
- pyradiosky/tests/test_skymodel.py
Adds a method to write a HEALPix + frequency sky model to the HDF5 format. This is necessary for the benchmarking branch on `pyuvsim`.
Also cleans up the HEALPix reader tests a little.
> Write healpix

- CHANGELOG.md
- pyradiosky/spherical_coords_transforms.py
- pyradiosky/tests/test_spherical_coords_transforms.py
In `rotate_points_3d` in `spherical_coords_transforms`, there's an arccos function, the argument of which can be _slightly_ bigger than 1 in the case that the point is rotated near to the pole of the coordinate system.  Forced it to be exactly 1 if it's close to 1 with an absolute tolerance of 1e-12.
Closes #6
> Fixed a tolerance issue on arccos of slightly >1

- pyradiosky/__init__.py
Add the `read_gleam_catalog` function to the pyradiosky namespace.
> put read_gleam_catalog in namespace

- pyradiosky/skymodel.py
Some tests in `hera_sim` were trying to access the `flux_density_I` column of the recarray (from `skymodel_to_array`). This change aliases the name "flux_density_I" to the "I" column, and likewise for the other Stokes parameters, for backwards compatibility.
Ideally, it would only issue the DeprecationWarning when you tried to access `flux_density_I`, but making that happen would involve subclassing numpy.ndarray, so the DeprecationWarning is issued when `skymodel_to_array` is run.
> alias deprecated field names in recarray

- CHANGELOG.md
- pyradiosky/skymodel.py
- pyradiosky/tests/test_skymodel.py
Adds a new method to SkyModel that will evaluate the Stokes array at a given set of frequencies, depending on the spectral_type, returning a new SkyModel (or modifying in-place) which has spectral_type "full".
- If spectral_type is "full", check that the requested frequencies are a subset of the existing frequencies and select those. Otherwise, error.
- If spectral_type is "sub-band", interpolate using scipy.interpolate.interp1d (freq_interp_kind controls the order). Additional interpolation methods can be added in future work.
- If spectral_type is "spectral_index", evaluate at the new frequencies.
- If flat, return a "full" freq SkyModel with the fluxes copied Nfreqs times. (Not really useful, but included for completeness).
Closes #52
> Evaluate Stokes

- CHANGELOG.md
- pyradiosky/skymodel.py
- pyradiosky/tests/test_skymodel.py
- pyradiosky/tests/test_utils.py
- pyradiosky/utils.py
Make the `stokes` and `coherency_radec` parameters be Quantity objects with units compatible with [Jy] or [K sr] for point like components and [Jy/sr] or [K] for healpix like components.
closes #7
closes #8
closes #73
closes #22
> make stokes be a quantity

- CHANGELOG.md
- pyradiosky/skymodel.py
- pyradiosky/tests/test_skymodel.py
Rename method that reads FHD catalog files to better match what it does.
closes #71
> rename `read_idl_catalog` to `read_fhd_catalog`

- pyradiosky/skymodel.py
Use `units.quantity.allclose` in the future equality tests rather than numpy's allclose.
Fixes an error seen in the tests for #91 that are unrelated to that PR's changes.
> Fix the future equality checks for ra & dec to use astropy's Quantity allclose

- CHANGELOG.md
- pyradiosky/skymodel.py
- pyradiosky/tests/test_skymodel.py
This PR adds a `from_xxx` *class*method for every `read_xxx` method existing on `SkyModel`, as well as changing `from_recarray` to a classmethod. This means that new objects can be created using the syntax
```
skyobj = SkyModel.from_gleam_catalog(fname)
```
Instead of the more laborious (and a little confusing)
```
skyobj = SkyModel()
skyobj.read_gleam_catalog(fname)
```
I changed all applicable instances of such reading in the tests to use the `from_xxx` classmethod. I did not remove the `read_xxx` methods, as that would break backwards compatibility, and I guess those might still be useful. I recommend thinking about whether these should be deprecated. 
Nothing in this PR should be backwards incompatible -- it merely adds new methods.
Fixes #87 
I think this is the more pythonic way to …
> Add classmethods to create SkyModel instances from different formats

- CHANGELOG.md
- pyradiosky/skymodel.py
Fixed some missed parameters in `__init__` and a bug in `read_fhd_catalog` that was exposed by the init fixes.
fixes # 89
> fix missed parameters in init, fix extended model group bug in read_fhd

- CHANGELOG.md
- pyradiosky/skymodel.py
- pyradiosky/tests/test_skymodel.py
Enables tolerance when comparing frequencies in the `at_frequencies` method.
When running `at_frequencies` on a SkyModel with spectral type "full", at_frequencies will attempt to select the requested frequencies from the existing array. Currently, this is done using `numpy.isin`, which requires an exact match. These changes allow frequencies to match to some tolerance in the search, defaulting to 1 Hz but settable with a keyword.
closes #82
> enable tolerance when selecting frequencies

- pyradiosky/tests/test_utils.py
- pyradiosky/utils.py
- scripts/download_gleam.py
Modify the GLEAM download utility to download all columns and the remove the ones that are not required to ensure that we get all the required columns. We weren't catching this with our unit tests because they use to only use the flat spectral type, which only required the first few columns. This PR adds testing with all the possible spectral types to ensure that all the columns are present.
fixes #105
> Fix the Gleam download to ensure it gets all the needed columns

- CHANGELOG.md
- ci/min_deps.yaml
- ci/tests.yaml
I forgot to update the changelog for PR #106. This remedies that.
It also limits us to not use astropy 4.2 until np.shape() works on Time objects (see #108)
> Update changelog for PR #106

- pyradiosky/tests/test_utils.py
Adds a unit test of `utils.jy_to_ksr` which compares the astropy-based calculation used by the utility function to a non-astropy equivalent.
There wasn't any test of this function before, and so an astropy-related error came up undetected.
> Unit test for jy_to_ksr function

- README.md
- ci/docs.yaml
- ci/min_deps.yaml
- ci/publish.yaml
- ci/pyuvsim.yaml
- ci/tests.yaml
- environment.yaml
- pyradiosky/tests/test_skymodel.py
- setup.py
Require pyuvdata >=2.1.3 to fix issues seen under astropy 4.2.
Also update warning checking for changes in pyuvdata warning messages.
I also removed our version requirement on numpy (used to be `>1.15.0`) because pyuvdata specifies `>1.18.0`, so the pyuvdata requirement seems sufficient.
closes #108
> Use pyuvdata 2.1.3

- CHANGELOG.md
- pyradiosky/skymodel.py
- pyradiosky/tests/test_skymodel.py
Change the default GLEAM spectral type from "flat" to "subband" which is a better default for science.
fixes #103
> Change the default spectral_type for GLEAM to `subband`

- CHANGELOG.md
- pyradiosky/skymodel.py
- pyradiosky/tests/test_skymodel.py
Better handle lists of Quantities used to initialize a SkyModel object. This used to error with a very confusing error message. Now if the lists contain compatible Quantities it just works (except for the Stokes parameter which must be an array), otherwise it gives a more helpful error message.
I also fixed a few things to deal with new deprecation warnings in numpy 1.20.
fixes #99
> Improve handling for init params passed as lists

- CHANGELOG.md
- pyradiosky/skymodel.py
- pyradiosky/tests/test_skymodel.py
Adds a new parameter "hpx_order" to indicate if healpix pixels are in ring or nested order.
Users should be able to control and check what ordering is used. Currently , it quietly defaults to ring ordering.
Fixes #133
> Add healpix pixel ordering parameter hpx_order

- .github/workflows/testsuite.yaml
pins the codecov github action at v1.5.2 until codecov/codecov-action#372 is resolved the master branch for the action is broken.
> pin last release of codecov action since main branch is broken

- pyradiosky/skymodel.py
- pyradiosky/tests/test_skymodel.py
When converting a SkyModel object from a component type of healpix to point, `self.name` is set as a list.  If you attempt to use any select functions like `source_cuts` after calling `healpix_to_point`, a TypeError is raised because lists do not support the indexing used in `select`.  This issue is fixed by casting `self.name` to a numpy array in `healpix_to_point`.  This branch modifies one line in `healpix_to_point` and adds a test to `test_skymodel.py` (the name can be changed if need be, but I added a description of what the test is intended to check.)
I think this is addressed above in the description?  Just a niche bug fix.
Should I update the CHANGELOG for this minor change?
> SkyModel.name as array, not list, after healpix_to_point

- CHANGELOG.md
- pyradiosky/skymodel.py
- pyradiosky/tests/test_skymodel.py
Ensure that the `hpx_order` parameter is round tripped properly through the various conversion, read and write methods. Set it as a required parameter for healpix objects (this is backwards compatible because if it doesn't exist it is defaulted to 'ring' as it was being handled in the past).
Also improve the future equality warning which was very confusing and cleanup test warnings.
closes #140 
We agreed in #134 to make hpx_order required for Healpix objects, but that was accidentally only implemented for the init function, not for the object. Since it wasn't required, we didn't notice that it wasn't being round tripped properly because when that happened it raised the future equality error which deceptively suggested the problem was to do with the frequency parameters rather than the …
> Fix handling of hpx_order throughout, improve future equality warning

- pyradiosky/skymodel.py
- pyradiosky/tests/test_skymodel.py
Provide a better error message when SkyModel is initialized with a stokes array that is the incorrect shape (doesn't match the other input shapes)
Fixes #142
> Improve the error message for initializing with wrong stokes shape

- pyradiosky/skymodel.py
- pyradiosky/tests/test_skymodel.py
Use the `get_lon_lat` method rather than directly accessing the attributes in the `source_cuts` method. Add a test that uses source_cuts on a healpix object.
The `source_cuts` method still directly accessed the log/lat attributes but those are not required to be set on Healpix objects. This causes a DeprecationWarning to be raised, which was missed because there was not a test of using that method on a healpix object.
> Fix lat/lon access in source_cuts method

- .pre-commit-config.yaml
- CHANGELOG.md
- pyradiosky/skymodel.py
- pyradiosky/tests/test_skymodel.py
- Add options to the `select` method to support selecting on coordinate ranges (`lat_range` and `lon_range`).
- Move support for flux cuts to `select` method
- Move non-rising cut to `cut_nonrising` method
- Move rise/set list calculation to `calculate_rise_set_lsts` method
- Deprecate `source_cuts` so there aren't two functions that seem to do the same job
fixes #156
> Add support for selecting based on coordinates

- CHANGELOG.md
- pyradiosky/skymodel.py
- pyradiosky/tests/test_skymodel.py
Fix a bug in `concat` when spectral type is not "spectral_index" but the spectral_index parameter is not None on at least one of the objects.
Restructured the handling of all optional parameters with an axis of length Ncomponents in `concat` to consolidate code and make it easier to add more such parameters in the future.
fixes #160
> Improve handling of optional parameters in concat

- CHANGELOG.md
- pyradiosky/skymodel.py
- pyradiosky/tests/test_skymodel.py
Fixed a bug where all the values in the output stokes array were NaN after calling `at_frequencies` on a subband object with some NaNs on a few sources in the stokes array.
Added the `nan_handling` keyword to the `at_frequencies` method to specify how NaNs in the stokes array are handled when interpolating subband spectral_type objects. These are handled per-component. Options are:
- "propagate": set all the output stokes to NaN if any input stokes are NaN
- "interp": interpolate using only the non-NaN values. If there are requested frequencies outside the non-NaN values for a source, set the stokes array at those frequencies to NaN.
- "clip": interpolate using only the non-NaN values. If there are requested frequencies outside the non-NaN values for a source, set the stokes array at …
> fix `at_frequencies` interpolation if there are NaNs in the stokes array

- pyradiosky/tests/test_skymodel.py
These are sourced from pyuvdata. It's been fixed in pyuvdata, but that fix will only be in versions > 2.2.6, so we need handling for it in the tests. Implemented here with a try/catch and labelled for removal when we require higher pyuvdata versions.
This is breaking tests on other PRs.
> Fix test errors from distutils deprecation warnings

- .github/workflows/externaltests.yaml
- .github/workflows/testsuite.yaml
Add a CI check that there are no unhandled warnings in the test suite. Similar to recently added warnings checks on pyuvdata and pyuvsim.
> Add a CI check for warnings in the test suite

- CHANGELOG.md
- pyradiosky/skymodel.py
- pyradiosky/tests/test_skymodel.py
> Deprecate the to/from_recarray methods

- CHANGELOG.md
- pyradiosky/skymodel.py
- pyradiosky/tests/test_skymodel.py
Add generic read and from_file methods that can accept any (non-deprecated) file type supported by SkyModel. This is based off code that currently exists in pyuvsim but that should live here.
Closes #121
> Add generic `read` and `from_file` methods

- CHANGELOG.md
- README.md
- ci/min_deps.yaml
- ci/publish.yaml
- ci/tests.yaml
- environment.yaml
- pyradiosky/skymodel.py
- setup.py
Add support for the `allowed_failures` parameter in `SkyModel.__eq__` to match the parameter added to `pyuvdata.UVBase.__eq__` in version 2.2.1.
> Add allowed_failures parameter to SkyModel.__eq__ to match UVBase

- .github/workflows/externaltests.yaml
- .github/workflows/publish-to-test-pypi.yaml
- .github/workflows/testsuite.yaml
- ci/min_versions.yaml
- ci/tests.yaml
- docs/tutorial.rst
- pyradiosky/skymodel.py
- pyradiosky/tests/test_skymodel.py
Tests were broken by a recent change to UVBase in pyuvdata and by a new astropy deprecation warning being triggered in lunarsky (I just filtered those for now, they need to be fixed in lunarsky). I also add a min versions CI.
> fix tests for new pyuvdata updates, new astropy deprecation warnings

- docs/tutorial.rst
- pyradiosky/tests/test_skymodel.py
- pyradiosky/tests/test_utils.py
pytest.raises should only be called on one line of code.
Fix some new pre-commit errors, mostly related to a new check in flake8-bugbear that flags `pytest.raises` calls that contain more than one line of code. Also work around an annoying isort error.
> fix new pre-commit errors from flake8-bugbear

- scripts/make_flat_spectrum_eor.py
make_flat_spectrum_eor.py now accepts a coordinate frame to be input. If a frame is not specified, it defaults to ICRS.
Previously, make_flat_spectrum_eor.py expected a frame to be specified for its returned SkyModel, but could not accept one as input. 
[](https://github.com/RadioAstronomySoftwareGroup/pyradiosky/issues/210)
> fix make_flat_spectrum_eor.py not accepting a frame

- .github/workflows/testsuite.yaml
- CHANGELOG.md
- README.md
- ci/full_deps.yaml
- ci/min_deps.yaml
- ci/min_versions.yaml
- ci/publish.yaml
- docs/tutorial.rst
- environment.yaml
- pyproject.toml
- setup.py
- src/pyradiosky/skymodel.py
- tests/test_skymodel.py
Added a new SkyModel attribute, `extra_columns`, which is a recarray and can support additional per-component info.
fixes #126
> Add `extra_columns` attribute to store other per-component catalog info

- CHANGELOG.md
- docs/tutorial.rst
- src/pyradiosky/skymodel.py
- tests/test_skymodel.py
The units on FHD catalogs are always in MHz but were being read in as if they were in Hz. This fixes that.
fixes #213
> fix the units on FHD reference frequencies

- .gitignore
- CHANGELOG.md
- README.md
- docs/references/skyh5_memo.tex
- docs/tutorial.rst
- src/pyradiosky/skymodel.py
- tests/test_skymodel.py
Add a memo to describe the file format. Note: I haven't yet added the pdf to the repo but it needs to be added before this PR is merged and I can add it at any time if it would help with the review.
Also changed the location in the SkyH5 file where the data-sized optional arrays (stokes_error and beam_amp) are saved. They were moved from the Header datagroup to the Data datagroup.
closes #118
> Add a SkyH5 memo describing the file format

- README.md
Add citation information for our JOSS paper to the readme.
> Add JOSS reference

- CHANGELOG.md
- pyproject.toml
- src/pyradiosky/skymodel.py
- tests/test_skymodel.py
Serial concatenation currently fails because `astropy.coordinates.concatenate` fails with serial concatenation. This PR removes the call to `concatenate` and just passes a list of SkyCoord objects to the SkyCoord constructor, which doesn't error.
fixes #245
> Fix serial concats

- CHANGELOG.md
- docs/tutorial.rst
- src/pyradiosky/skymodel.py
- tests/test_skymodel.py
Fix some imports for pyuvdata v3 and fix compatibility with numpy 2.0
> Make imports work with current and future pyuvdata, fix compatibility with numpy 2.0

- CHANGELOG.md
- README.md
- ci/full_deps.yaml
- ci/min_deps.yaml
- ci/min_versions.yaml
- ci/publish.yaml
- docs/references/skyh5_memo.tex
- environment.yaml
- pyproject.toml
- src/pyradiosky/skymodel.py
- tests/test_skymodel.py
Replaces the ad hoc analytic short dipole used in our testing of polarized sources with the pyuvdata analytic short dipole beam.
This requires bumping the minimum pyuvdata version to v3.1.0.
I also bumped the minimum lunarsky version to 0.2.5 for compatibility with astropy 6.0
> Use the new pyuvdata analytic short dipole beam in our polarized source test.

- docs/tutorial.rst
The tutorial material on local frame calculations were all buried under "convenience methods" and it wasn't clear that you had to call `update_position` to get any of it to work.
> better highlight local frame attributes and methods

- CHANGELOG.md
- docs/conf.py
- src/pyradiosky/skymodel.py
- tests/test_skymodel.py
Add option to skip reading optional params from skyH5 files, e.g. names for Healpix files.
closes #266
> Add option to skip optional params on read.

- .github/workflows/externaltests.yaml
- .github/workflows/publish-to-test-pypi.yaml
- .github/workflows/testsuite.yaml
- .readthedocs.yml
- CHANGELOG.md
- README.md
- ci/full_deps.yaml
- ci/min_deps.yaml
- ci/min_versions.yaml
- ci/publish.yaml
- environment.yaml
- pyproject.toml
- tests/test_skymodel.py
We should be testing against 3.13. I dropped 3.10 to not increase the number of versions we're testing against and because we've already dropped it for pyuvdata.
Also updated a few minimum dependency versions:
- scipy >= 1.9
- h5py >= 3.7
None of these are bleeding edge, they're all fairly old.
> Test against python 3.13, drop support for python 3.10

- CHANGELOG.md
- docs/tutorial.rst
- src/pyradiosky/skymodel.py
- tests/test_skymodel.py
- tests/test_utils.py
This adds two new options to select:
- `non_nan` to select components that do not have NaN values in the `stokes` parameter at either any or all frequencies.
- `non-negative` to select components with non-negative Stokes I values (negative Stokes Q, U and V are meaningful)
These are helpful for GLEAM, which has both of these issues. I updated the tutorial section on reading in GLEAM with more information about these issues and the spectral types.
I also added some warnings to the `check` method to inform users if these issues are present in their SkyModel object. These only happen if `run_check_acceptibility` is True (which is the default).
I also discovered that on file reads we were calling the `__init__` method but not passing the checking options through to `__init__`, which always …
> Add option to select components with non-nan stokes values and non-negative stokes I values

- src/pyradiosky/skymodel.py
- tests/test_skymodel.py
Provide useful error messages when required parameters are not passed for generic reads of VOT files.
Fixes #200
> Provide better error messages when reading VOT files with generic read

- .github/workflows/externaltests.yaml
- .github/workflows/publish-to-test-pypi.yaml
- .github/workflows/testsuite.yaml
Ensure that conda "defaults" channel is not used. Note that even with this fix there are still some warnings about this but they seem to be unavoidable and the number of warnings is now reduced.
> fix warnings about default channel on CI runs that use conda

- .github/workflows/publish-to-test-pypi.yaml
The publish to pypi step recently failed on pyuvsim. This propagates the fix to this repo.
> fix the publish to pypi action
